### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by EvanDaley** [ory/client-ruby#2]
It looks like the ruby client is at least partially documented in the source repo. 
https://github.com/ory/sdk/tree/master/clients/client/ruby

Suggestion: copy the readme from that page into this repo each time you build this repo.

**Comment by EvanDaley** [comment]
Great info here too
https://github.com/ory/sdk/blob/master/clients/keto/ruby/docs/ReadApi.md

**Comment by aeneasr** [comment]
That's a good point - @vinckr @tomekpapiernik any ideas how we can include these docs in our normal docs?

**Comment by vinckr** [comment]
We can link to them in the [SDK overview](https://www.ory.sh/docs/sdk). 

maybe a table like so:

| Language | Download SDK                                         | Documentation                                                                                                                                                       |
| -------- | ---------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Ruby     | [rubygems.org](https://rubygems.org/gems/ory-client) | [README](https://github.com/ory/sdk/blob/master/clients/client/ruby/README.md), [ReadApi](https://github.com/ory/sdk/blob/master/clients/keto/ruby/docs/ReadApi.md) |

...

WDYT?

**Comment by EvanDaley** [comment]
I like that idea. I think mainly we would want to add documentation links on this page tho (most devs probably go straight to the gem readme): https://github.com/ory/client-ruby
