### ISSUE TITLE
Server settings - local host is not possible

### ISSUE THREAD

**Issue by EvanDaley** [ory/client-ruby#4]
We should update the server_settings method to allow developers to override the url. It doesn't look like @host and @base_path are respected.

In order to make this gem work with the Keto docker image, I had to override `url` to a specific localhost value.

![image](https://user-images.githubusercontent.com/6478694/210681057-38ea84fa-cab4-4d2c-bb39-2f83812955fb.png)

Ideally this would be controlled by an env variable. Should I PR a fix into the main repo?

**Comment by aeneasr** [comment]
https://github.com/ory/sdk/issues/243#issuecomment-1372171073
