### ISSUE TITLE
Whelp - wrong URL for expand?

### ISSUE THREAD

**Issue by EvanDaley** [ory/client-ruby#5]
This appears to be the wrong URL in the permissions_api.rb file:

![image](https://user-images.githubusercontent.com/6478694/210681347-8370b6fa-0d06-4e9a-b479-1068d543d401.png)

I believe we want `local_var_path = '/expand'`

![image](https://user-images.githubusercontent.com/6478694/210681444-41b0a0b7-2d92-4f5f-a0fb-a9cc7ef0083d.png)

`/relation-tuples/expand` doesn't work with the current docker image but `/expand` does

Please advise 🙏

**Comment by EvanDaley** [comment]
Let me know if I should open these issues against the main https://github.com/ory/sdk repo. I've got fixes for all of them, but could use some direction in regards to your PR/release process. Thanks

**Comment by aeneasr** [comment]
https://github.com/ory/sdk/issues/243#issuecomment-1372171073
